name: dr
description: home healers dr

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.1+52

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  bloc: ^8.1.3
  equatable: ^2.0.5
  shimmer: ^3.0.0
  http: ^1.1.0
  shared_preferences: ^2.2.0
  logger: ^2.0.1
  flutter_bloc: ^8.1.4
  easy_localization: ^3.0.2
  flutter_svg: ^2.0.7
  image_picker: ^1.0.4
  carousel_slider: ^4.2.1
  table_calendar: ^3.0.9
  file_picker: ^6.1.1
  map_location_picker: ^1.2.8+3
  get_it: ^7.6.4
  bot_toast: ^4.1.1
  photo_view: ^0.14.0
  number_to_character: ^0.0.12
  pdf: ^3.10.4
  path_provider: ^2.1.1
  simple_html_css: ^4.0.0
  maps_launcher: ^2.2.0
  url_launcher: ^6.1.14
  flutter_pdfview: ^1.3.2
  flutter_inappwebview: ^6.0.0
  firebase_messaging: ^14.7.1
  firebase_core: ^2.19.0
  flutter_local_notifications: ^16.1.0
  intl_phone_field: ^3.2.0
  barcode_widget: ^2.0.4

  printing: ^5.12.0
  pusher_channels_flutter: ^2.2.1
  map_launcher: ^3.0.1
  flutter_share: ^2.0.0
  firebase_analytics: ^10.7.4
  uni_links: ^0.5.1
  uri: ^1.0.0
  flutter_verification_code: ^1.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: '^0.13.1'

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icons/logo_icon.jpg'
  min_sdk_android: 21

  flutter_lints: ^2.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Tajawal-Regular
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
